#!/bin/bash

# ARESA Studio - Test Environment Setup Script
# This script configures test database connections for ARESA
#
# Usage: ./setup-test-connections.sh
#
# Prerequisites:
#   - Docker containers running (docker-compose up -d)
#   - ARESA CLI installed

set -e

echo "╔════════════════════════════════════════════════════════════╗"
echo "║          ARESA Studio - Test Environment Setup             ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Configuration
POSTGRES_HOST="localhost"
POSTGRES_PORT="5433"
POSTGRES_USER="aresa"
POSTGRES_PASS="aresa_test_123"
POSTGRES_DB="aresa_test"

MYSQL_HOST="localhost"
MYSQL_PORT="3307"
MYSQL_USER="aresa"
MYSQL_PASS="aresa_test_123"
MYSQL_DB="aresa_test"

CLICKHOUSE_HOST="localhost"
CLICKHOUSE_PORT="8124"
CLICKHOUSE_USER="aresa"
CLICKHOUSE_PASS="aresa_test_123"
CLICKHOUSE_DB="aresa_test"

# Mock Cloud Services (Snowflake & Databricks)
MOCK_CLOUD_HOST="localhost"
MOCK_CLOUD_PORT="8443"

# Check if docker containers are running
check_containers() {
    echo -e "${CYAN}Checking Docker containers...${NC}"

    if ! docker ps | grep -q "aresa-test-postgres"; then
        echo -e "${YELLOW}⚠ PostgreSQL container not running${NC}"
        return 1
    fi
    echo -e "${GREEN}✓ PostgreSQL container running${NC}"

    if ! docker ps | grep -q "aresa-test-mysql"; then
        echo -e "${YELLOW}⚠ MySQL container not running${NC}"
        return 1
    fi
    echo -e "${GREEN}✓ MySQL container running${NC}"

    if ! docker ps | grep -q "aresa-test-clickhouse"; then
        echo -e "${YELLOW}⚠ ClickHouse container not running${NC}"
        return 1
    fi
    echo -e "${GREEN}✓ ClickHouse container running${NC}"

    if ! docker ps | grep -q "aresa-test-mock-cloud"; then
        echo -e "${YELLOW}⚠ Mock Cloud container not running${NC}"
        return 1
    fi
    echo -e "${GREEN}✓ Mock Cloud server running (Snowflake + Databricks)${NC}"

    return 0
}

# Wait for databases to be ready
wait_for_databases() {
    echo ""
    echo -e "${CYAN}Waiting for databases to be ready...${NC}"

    # Wait for PostgreSQL
    echo -n "  PostgreSQL: "
    for i in {1..30}; do
        if docker exec aresa-test-postgres pg_isready -U $POSTGRES_USER -d $POSTGRES_DB > /dev/null 2>&1; then
            echo -e "${GREEN}Ready${NC}"
            break
        fi
        if [ $i -eq 30 ]; then
            echo -e "${RED}Timeout${NC}"
            exit 1
        fi
        sleep 1
        echo -n "."
    done

    # Wait for MySQL
    echo -n "  MySQL: "
    for i in {1..30}; do
        if docker exec aresa-test-mysql mysqladmin ping -h localhost -u $MYSQL_USER -p$MYSQL_PASS > /dev/null 2>&1; then
            echo -e "${GREEN}Ready${NC}"
            break
        fi
        if [ $i -eq 30 ]; then
            echo -e "${RED}Timeout${NC}"
            exit 1
        fi
        sleep 1
        echo -n "."
    done

    # Wait for ClickHouse
    echo -n "  ClickHouse: "
    for i in {1..30}; do
        if curl -s "http://$CLICKHOUSE_HOST:$CLICKHOUSE_PORT/?query=SELECT%201" > /dev/null 2>&1; then
            echo -e "${GREEN}Ready${NC}"
            break
        fi
        if [ $i -eq 30 ]; then
            echo -e "${RED}Timeout${NC}"
            exit 1
        fi
        sleep 1
        echo -n "."
    done

    # Wait for Mock Cloud Server
    echo -n "  Mock Cloud: "
    for i in {1..30}; do
        if curl -s "http://$MOCK_CLOUD_HOST:$MOCK_CLOUD_PORT/health" > /dev/null 2>&1; then
            echo -e "${GREEN}Ready${NC}"
            break
        fi
        if [ $i -eq 30 ]; then
            echo -e "${RED}Timeout${NC}"
            exit 1
        fi
        sleep 1
        echo -n "."
    done
}

# Create ARESA config file with test connections
create_aresa_config() {
    echo ""
    echo -e "${CYAN}Creating ARESA test configuration...${NC}"

    # Find or create config directory
    CONFIG_DIR="${HOME}/.config/aresa"
    CONFIG_FILE="${CONFIG_DIR}/config.yaml"
    TEST_CONFIG_FILE="${CONFIG_DIR}/config.test.yaml"

    mkdir -p "$CONFIG_DIR"

    # Create test config file
    cat > "$TEST_CONFIG_FILE" << EOF
# ARESA Studio - Test Configuration
# Auto-generated by setup-test-connections.sh
# DO NOT EDIT - This file is for testing purposes only

sources:
  # PostgreSQL Test Database
  test-postgres:
    type: postgres
    uri: "postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    description: "PostgreSQL test database with sample data"

  # MySQL Test Database
  test-mysql:
    type: mysql
    uri: "mysql://${MYSQL_USER}:${MYSQL_PASS}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}"
    description: "MySQL test database with sample data"

  # ClickHouse Test Database
  test-clickhouse:
    type: clickhouse
    host: "${CLICKHOUSE_HOST}"
    port: ${CLICKHOUSE_PORT}
    user: "${CLICKHOUSE_USER}"
    password: "${CLICKHOUSE_PASS}"
    database: "${CLICKHOUSE_DB}"
    description: "ClickHouse analytics test database"

  # SQLite Test Database (local file)
  test-sqlite:
    type: sqlite
    uri: "${CONFIG_DIR}/test.db"
    description: "SQLite local test database"

  # Snowflake Mock (uses local mock server)
  test-snowflake:
    type: snowflake
    account: "mock-account"
    warehouse: "TEST_WH"
    database: "MOCK_DB"
    schema: "PUBLIC"
    host: "${MOCK_CLOUD_HOST}"
    port: ${MOCK_CLOUD_PORT}
    username: "mock_user"
    password: "mock_password"
    description: "Snowflake mock database for testing"

  # Databricks Mock (uses local mock server)
  test-databricks:
    type: databricks
    host: "${MOCK_CLOUD_HOST}"
    port: ${MOCK_CLOUD_PORT}
    catalog: "main"
    schema: "default"
    token: "mock_databricks_token"
    description: "Databricks mock database for testing"

defaults:
  output: table
  limit: 100
EOF

    echo -e "${GREEN}✓ Created test config: ${TEST_CONFIG_FILE}${NC}"
}

# Create SQLite test database
create_sqlite_db() {
    echo ""
    echo -e "${CYAN}Creating SQLite test database...${NC}"

    SQLITE_DB="${HOME}/.config/aresa/test.db"

    # Remove old database if exists
    rm -f "$SQLITE_DB"

    # Create database with sample data
    sqlite3 "$SQLITE_DB" << 'EOF'
-- Create tables
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    content TEXT,
    views INTEGER DEFAULT 0,
    published BOOLEAN DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE comments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    post_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    content TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES posts(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Create view
CREATE VIEW post_summary AS
SELECT
    p.id,
    p.title,
    u.username AS author,
    p.views,
    COUNT(c.id) AS comment_count
FROM posts p
JOIN users u ON p.user_id = u.id
LEFT JOIN comments c ON p.id = c.post_id
GROUP BY p.id;

-- Insert sample data
INSERT INTO users (username, email, full_name) VALUES
('alice', 'alice@example.com', 'Alice Johnson'),
('bob', 'bob@example.com', 'Bob Smith'),
('carol', 'carol@example.com', 'Carol Williams');

INSERT INTO posts (user_id, title, content, views, published) VALUES
(1, 'Getting Started with SQL', 'SQL is a powerful language...', 150, 1),
(1, 'Advanced Query Techniques', 'In this post we explore...', 89, 1),
(2, 'Database Design Best Practices', 'Good database design starts with...', 234, 1),
(3, 'Performance Optimization Tips', 'Here are some tips...', 45, 0);

INSERT INTO comments (post_id, user_id, content) VALUES
(1, 2, 'Great introduction!'),
(1, 3, 'Very helpful, thanks!'),
(2, 3, 'Looking forward to more posts like this.'),
(3, 1, 'Excellent advice!');
EOF

    echo -e "${GREEN}✓ Created SQLite database: ${SQLITE_DB}${NC}"
}

# Print test connection summary
print_summary() {
    echo ""
    echo "════════════════════════════════════════════════════════════"
    echo -e "${GREEN}✓ Test Environment Setup Complete!${NC}"
    echo "════════════════════════════════════════════════════════════"
    echo ""
    echo "Test connections configured:"
    echo ""
    echo -e "  ${CYAN}test-postgres${NC}"
    echo "    Type: PostgreSQL"
    echo "    Host: ${POSTGRES_HOST}:${POSTGRES_PORT}"
    echo "    Database: ${POSTGRES_DB}"
    echo "    Tables: employees, departments, orders, products"
    echo "    Views: employee_summary, order_stats"
    echo ""
    echo -e "  ${CYAN}test-mysql${NC}"
    echo "    Type: MySQL"
    echo "    Host: ${MYSQL_HOST}:${MYSQL_PORT}"
    echo "    Database: ${MYSQL_DB}"
    echo "    Tables: customers, products, orders, order_details, inventory_log"
    echo "    Views: customer_orders_summary, product_sales"
    echo ""
    echo -e "  ${CYAN}test-clickhouse${NC}"
    echo "    Type: ClickHouse"
    echo "    Host: ${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT}"
    echo "    Database: ${CLICKHOUSE_DB}"
    echo "    Tables: events, page_views, user_metrics, sales, server_metrics"
    echo "    Views: daily_events_summary, sales_by_region"
    echo ""
    echo -e "  ${CYAN}test-sqlite${NC}"
    echo "    Type: SQLite"
    echo "    Path: ~/.config/aresa/test.db"
    echo "    Tables: users, posts, comments"
    echo "    Views: post_summary"
    echo ""
    echo -e "  ${CYAN}test-snowflake${NC} (Mock)"
    echo "    Type: Snowflake (Mock Server)"
    echo "    Host: ${MOCK_CLOUD_HOST}:${MOCK_CLOUD_PORT}"
    echo "    Database: MOCK_DB / PUBLIC"
    echo "    Tables: EMPLOYEES, PRODUCTS"
    echo "    Views: EMPLOYEE_SUMMARY"
    echo ""
    echo -e "  ${CYAN}test-databricks${NC} (Mock)"
    echo "    Type: Databricks (Mock Server)"
    echo "    Host: ${MOCK_CLOUD_HOST}:${MOCK_CLOUD_PORT}"
    echo "    Catalog: main / default"
    echo "    Tables: employees, products"
    echo "    Views: employee_summary"
    echo ""
    echo "════════════════════════════════════════════════════════════"
    echo ""
    echo "To start ARESA Studio with test config:"
    echo ""
    echo -e "  ${YELLOW}ARESA_CONFIG=~/.config/aresa/config.test.yaml aresa serve${NC}"
    echo ""
    echo "Or merge test connections into your main config manually."
    echo ""
}

# Main execution
main() {
    if ! check_containers; then
        echo ""
        echo -e "${YELLOW}Start containers first with:${NC}"
        echo "  cd $(dirname $0)"
        echo "  docker-compose up -d"
        echo ""
        exit 1
    fi

    wait_for_databases
    create_aresa_config
    create_sqlite_db
    print_summary
}

main "$@"

